language: node_js
node_js:
- '8'
script:
- npm run spec
notifications:
  email: false
  slack:
    secure: "Mzzn/SxceJA6+83aaYPiB7RqFDKfTQAeaNG/WlTxdAMeliwOIgrukAU4xwAbZuB/hwmbsMpMahjMhu0eVnB0aAl8PUZNBRiA4HI+q9haoQ/1sDOdKVjZFFKmikK5reXO7RoxhqXQx9ikEbpXGL3osl5Z/8OFjOujHyUuJS7yWPWbrZ31tX2S90413dp4lKrQ5pO5kiYcycuEsL9UZmjI1NQH4+Bjyxb55R4sGDuIQNggiNPSOrZX36X0m6kGJizjQGSPKNBtWRYcZSUfgaFmofHOqkUH3PZ5bv2p2wwacaF42JD+AGTanuHEJqJ6atCWkAlsIcPLJp4C7cbgKDDEs72eAPHk5hN3OmGGeLcRFik5Gx0gEgtnF7dUAYKsQJvBYgaetWfIbO6D38gTDbwD8h3lK4QgayEdiTlSSXpl5zxQKmx3dWA7NcP6Cn+6/0xPZ9UWlBXMlizhZhjDTdgBAco13UhLZ20mwyeG5622avvlYHYRi6Q22ud6aCDBPiXQl8Ta57DFi2c0SOOjZPnhUrsPt0+bQylZEMt6I1HkACss1iH+bndVA+B3DtaKm8XRiRulVbRn17TqPkbaiQ92xVnGSJtUFlvN7ijsWGIU6uVQ1w376NP7vyF54VTVVtc6OCjgfA+unKbdanZa4gwlHE7vH6ikEoL4pWvbI1eaTh8="
